version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: heroforce_db
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - heroforce_net

volumes:
  pgdata:

networks:
  heroforce_net:
